<?php

use Illuminate\Database\Seeder;

use App\Domain\Facades\Fees;

class FeeSeeder extends Seeder
{
	public function run()
	{
		Fees::create(array_map(function ($item) {
			return [
				'name' => $item[0],
				'points' => $item[1],
				'comment' => $item[2]
			];
		}, $this->fees));
		Fees::log(array_map(function ($item) {
			return [
				'name' => $item[0],
				'admin_id' => 0,
				'points' => $item[1],
				'comment' => 'auto generated by system scripts'
			];
		}, $this->fees));
	}

	protected $fees = [
		['fba_outbound_standard_new', 100, '出荷手数料(FBA) 標準以下 新品'],
		['fba_outbound_standard_used', 100, '出荷手数料(FBA) 標準以下 中古'],
		['fba_outbound_large_new', 100, '出荷手数料(FBA) 大型 新品'],
		['fba_outbound_large_used', 100, '出荷手数料(FBA) 大型 中古'],
		['fba_outbound_special', 100, '出荷手数料(FBA) 大型特殊'],
		['ida_outbound_standard_new', 100, '出荷手数料(個配) 標準以下 新品'],
		['ida_outbound_standard_used', 100, '出荷手数料(個配) 標準以下 中古'],
		['ida_outbound_large_new', 100, '出荷手数料(個配) 大型 新品'],
		['ida_outbound_large_used', 100, '出荷手数料(個配) 大型 新品'],
		['ida_outbound_special', 100, '出荷手数料(個配) 大型 新品'],
		['ida_standard_nationwide', 100, '個別配送料 標準以下 全国一律'],
		['ida_standard_hokkaido', 100, '個別配送料 標準以下 北海道'],
		['ida_standard_okinawa', 100, '個別配送料 標準以下 沖縄県・離島'],
		['ida_large_nationwide', 100, '個別配送料 大型 全国一律'],
		['ida_large_hokkaido', 100, '個別配送料 大型 北海道'],
		['ida_large_okinawa', 100, '個別配送料 大型 沖縄県・離島'],
		['ida_special_nationwide', 100, '個別配送料 大型特殊 全国一律'],
		['ida_special_hokkaido', 100, '個別配送料 大型特殊 北海道'],
		['ida_special_okinawa', 100, '個別配送料 大型特殊 沖縄県・離島'],
		['photograph_one', 100, '写真撮影 1枚'],
		['photograph_two', 100, '写真撮影 2枚'],
		['photograph_three', 100, '写真撮影 3枚'],
		['appandant_check', 100, '付属品確認'],
		['clean_standard', 100, 'クリーニング 標準以下'],
		['clean_large', 100, 'クリーニング 大型'],
		['repack', 100, 'セット梱包'],
		['check', 100, '動作確認'],
		['inbound', 100, '荷受け手数料'],
		['confirm', 100, '確認在庫'],
		['unexpected', 100, '不明在庫']
	];
}
